"""empty message

Revision ID: 0e6ff50c9a99
Revises: f6e18f33e14b
Create Date: 2021-04-12 14:59:13.975921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e6ff50c9a99'
down_revision = 'f6e18f33e14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'credit_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('invoice', 'user_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'user_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('invoice', 'credit_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
