"""empty message

Revision ID: 37a3c92b8c57
Revises: a682f62f36f2
Create Date: 2021-04-12 13:18:03.925683

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37a3c92b8c57'
down_revision = 'a682f62f36f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sent_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sent_to', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
