"""empty message

Revision ID: a682f62f36f2
Revises: cda4228d748a
Create Date: 2021-04-10 23:15:55.546405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a682f62f36f2'
down_revision = 'cda4228d748a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('credit_id', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'invoice', 'credit', ['credit_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'credit_id')
    # ### end Alembic commands ###
