"""empty message

Revision ID: f6e18f33e14b
Revises: 37a3c92b8c57
Create Date: 2021-04-12 14:45:35.500456

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6e18f33e14b'
down_revision = '37a3c92b8c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False))
    op.add_column('invoice', sa.Column('app_fee', sa.String(length=100), nullable=False))
    op.add_column('invoice', sa.Column('charged_amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False))
    op.add_column('invoice', sa.Column('currency', sa.String(length=100), nullable=True))
    op.add_column('invoice', sa.Column('orderRef', sa.String(length=100), nullable=False))
    op.add_column('invoice', sa.Column('txRef', sa.String(length=100), nullable=False))
    op.drop_column('invoice', 'amount_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('invoice', 'txRef')
    op.drop_column('invoice', 'orderRef')
    op.drop_column('invoice', 'currency')
    op.drop_column('invoice', 'charged_amount')
    op.drop_column('invoice', 'app_fee')
    op.drop_column('invoice', 'amount')
    # ### end Alembic commands ###
