"""empty message

Revision ID: f81d394057be
Revises: 0e6ff50c9a99
Create Date: 2021-04-12 15:20:36.458876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f81d394057be'
down_revision = '0e6ff50c9a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('txRef', sa.String(length=100), nullable=False),
    sa.Column('orderRef', sa.String(length=100), nullable=False),
    sa.Column('app_fee', sa.String(length=100), nullable=False),
    sa.Column('charged_amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2, asdecimal=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('invoice', 'charged_amount')
    op.drop_column('invoice', 'app_fee')
    op.drop_column('invoice', 'txRef')
    op.drop_column('invoice', 'orderRef')
    op.drop_column('invoice', 'currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('currency', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('invoice', sa.Column('orderRef', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoice', sa.Column('txRef', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoice', sa.Column('app_fee', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('invoice', sa.Column('charged_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_table('transaction')
    # ### end Alembic commands ###
